- plugins/org.eclipse.thym.ui.importer/.classpath
- plugins/org.eclipse.thym.ui.importer/.project
- plugins/org.eclipse.thym.ui.importer/.settings/org.eclipse.jdt.core.prefs
- plugins/org.eclipse.thym.ui.importer/.settings/org.eclipse.m2e.core.prefs
- plugins/org.eclipse.thym.ui.importer/META-INF/MANIFEST.MF
- plugins/org.eclipse.thym.ui.importer/build.properties
- plugins/org.eclipse.thym.ui.importer/plugin.xml
- plugins/org.eclipse.thym.ui.importer/pom.xml
- plugins/org.eclipse.thym.ui.importer/src/org/eclipse/thym/ui/importer/CordovaProjectConfigurator.java
- plugins/org.eclipse.thym.ui.importer/src/org/eclipse/thym/ui/importer/ThymImporterActivator.java
- plugins/pom.xml
- pom.xml
- repository/category.xml
- target-platforms/luna.R/luna.R.target
- target-platforms/mars.M/mars.M.target
Signed-off-by: Mickael Istria <mistria@redhat.com>
> Contribution to the smart importer framework

- plugins/org.eclipse.thym.wp.core/META-INF/MANIFEST.MF
- plugins/org.eclipse.thym.wp.core/pom.xml
- plugins/org.eclipse.thym.wp.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.thym.wp.ui/pom.xml
Add platform filters and update pom files of wp plugins.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=453701
Change-Id: I08289bfd0ac7f477a9e1475f44d1c5560365ec31
Signed-off-by: wgalanciak <wojciech.galanciak@gmail.com>
> [453701] Add support for Windows Phone 8 platform

- plugins/org.eclipse.thym.ui.importer/META-INF/MANIFEST.MF
- plugins/org.eclipse.thym.ui.importer/plugin.xml
- plugins/org.eclipse.thym.ui.importer/src/org/eclipse/thym/internal/ui/importer/CordovaProjectConfigurator.java
- plugins/org.eclipse.thym.ui.importer/src/org/eclipse/thym/internal/ui/importer/ThymImporterActivator.java
- target-platforms/luna.R/luna.R.target
- target-platforms/mars.M/mars.M.target
- tests/org.eclipse.thym.ui.importer.test/.classpath
- tests/org.eclipse.thym.ui.importer.test/.project
- tests/org.eclipse.thym.ui.importer.test/.settings/org.eclipse.jdt.core.prefs
- tests/org.eclipse.thym.ui.importer.test/META-INF/MANIFEST.MF
- tests/org.eclipse.thym.ui.importer.test/about.html
- tests/org.eclipse.thym.ui.importer.test/build.properties
- tests/org.eclipse.thym.ui.importer.test/pom.xml
- tests/org.eclipse.thym.ui.importer.test/src/org/eclipse/thym/ui/importer/test/ImportTest.java
- tests/pom.xml
+ Automated test
+ Move classes to internal
> Use newer Easymport APIs

- tests/pom.xml
Added profile for test to work on OSX
> Bug 484771 - Re-enable UI tests

- plugins/org.eclipse.thym.android.core/src/org/eclipse/thym/android/core/adt/AndroidLaunchDelegate.java
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488701
Signed-off-by: wjin <wjin@us.ibm.com>
> Bug488701 - app dose not launch when run the emulator for Android

- plugins/org.eclipse.thym.ui.importer/META-INF/MANIFEST.MF
- plugins/org.eclipse.thym.ui.importer/plugin.xml
- plugins/org.eclipse.thym.ui.importer/src/org/eclipse/thym/internal/ui/importer/CordovaProjectConfigurator.java
- target-platforms/neon.M/neon.M.target
- tests/org.eclipse.thym.ui.importer.test/META-INF/MANIFEST.MF
- tests/org.eclipse.thym.ui.importer.test/src/org/eclipse/thym/ui/importer/test/ImportTest.java
Signed-off-by: Mickael Istria <mistria@redhat.com>
> Migrate to Smart Import from Platform UI

- plugins/org.eclipse.thym.android.core/src/org/eclipse/thym/android/core/adt/AndroidLaunchDelegate.java
- plugins/org.eclipse.thym.android.core/src/org/eclipse/thym/android/core/adt/AndroidSDKManager.java
- plugins/org.eclipse.thym.android.core/src/org/eclipse/thym/android/core/adt/BuildDelegate.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/cordova/CordovaCLI.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/util/ExternalProcessUtility.java
Remove '-cpu-delay 0' paramater when launching android emulator.
Make sure that output of list android devices command is correctly processed
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=510623
> [510623]  Cannot run cordova project with android emulator

- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/engine/AvailableCordovaEnginesSection.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/wizard/project/EngineConfigurationPage.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=514688
> [514688] Validate EngineConfigurationPage after engine download/removal

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/engine/HybridMobileEngineManager.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/config/internal/EssentialsPage.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/properties/EnginePropertyPage.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/test/HybridMobileEngineTests.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=516525
> [516525] Add support for projects with no platform.

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/engine/HybridMobileEngineManager.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=516864
> [516864] Update platform only if version changed

- plugins/org.eclipse.thym.android.core/src/org/eclipse/thym/android/core/adt/BuildDelegate.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/HybridProject.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/config/WidgetModel.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/engine/HybridMobileEngineManager.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/cordova/CordovaCLI.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/cordova/CordovaProjectCLI.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/libraries/CordovaLibraryJsContainerInitializer.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/platform/AbstractProjectGeneratorDelegate.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/platform/PlatformPropertyTester.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/plugin/CordovaPluginManager.java
- plugins/org.eclipse.thym.ios.core/src/org/eclipse/thym/ios/core/xcode/XCodeBuild.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/config/internal/EssentialsPage.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/cordova/MissingCordovaStatusHandler.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/cordova/RequirementsUtility.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/project/RestoreProjectListener.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/properties/EnginePropertyPage.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/launch/HybridProjectLaunchShortcut.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/plugins/internal/PluginUninstallAction.java
- plugins/org.eclipse.thym.win.core/src/org/eclipse/thym/win/core/build/WinBuild.java
- plugins/org.eclipse.thym.win.core/src/org/eclipse/thym/win/internal/core/WinLaunchDelegate.java
- plugins/org.eclipse.thym.wp.core/src/org/eclipse/thym/wp/core/vstudio/MSBuild.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/HybridProjectTest.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/internal/cordova/CordovaCLITest.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/internal/cordova/CordovaProjectCLITest.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/hybrid/test/AllHybridTests.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517166
> [517166] Add basic project operations directly to HybridProject

- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/wizard/project/WizardNewHybridProjectCreationPage.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=516809
> [516809] Add check for cordova availability in new app wizard

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/plugin/CordovaPluginManager.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/wizard/project/HybridProjectCreator.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/wizard/project/NewHybridProjectWizard.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517233
> [517233] Improve progress reporting when creating new project

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/engine/HybridMobileEngineManager.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/plugin/CordovaPluginManager.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/internal/project/RestoreProjectListener.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/plugins/internal/CordovaPluginSelectionPage.java
- plugins/org.eclipse.thym.ui/src/org/eclipse/thym/ui/wizard/project/HybridProjectCreator.java
- tests/org.eclipse.thym.test/res/config.xml
- tests/org.eclipse.thym.test/res/configWithoutEngine.xml
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/test/HybridMobileEngineTests.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/hybrid/test/TestProject.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/ui/wizard/project/HybridProjectConvertTest.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=516875
> [516875] Call prepare for imported projects

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/engine/internal/cordova/CordovaEngineProvider.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/test/HybridMobileEngineTests.java
> Fix failing HybridMobileEngineTests

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/HybridCore.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/HybridProject.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/project/DerivedFoldersChangeListener.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/platform/PlatformConstants.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/core/HybridProjectTest.java
- tests/org.eclipse.thym.test/src/org/eclipse/thym/hybrid/test/TestProject.java
Mark platforms, plugins and node_modules subfolders as derived
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=506517
> [506517] Too many XML problems in platforms folder shown

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/engine/internal/cordova/NpmBasedEngineRepoProvider.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/internal/util/HttpUtil.java
- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/plugin/registry/CordovaPluginRegistryManager.java
Use HttpUtil class for all http connections.
All connections are using proxy and are cached.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517939
> [517939] Use proxy for all http connections

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/HybridCore.java
> Remove usage of deprecated PackageAdmin

- plugins/org.eclipse.thym.core/src/org/eclipse/thym/core/config/WidgetModel.java
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=526129
> [526129] Fix NPE when config.xml does not contain any plugin tag.

- tests/org.eclipse.thym.test/META-INF/MANIFEST.MF
- tests/org.eclipse.thym.test/src/org/eclipse/thym/hybrid/test/AllHybridTests.java
- tests/org.eclipse.thym.ui.test/META-INF/MANIFEST.MF
- tests/org.eclipse.thym.ui.test/about.html
- tests/org.eclipse.thym.ui.test/build.properties
- tests/org.eclipse.thym.ui.test/pom.xml
- tests/org.eclipse.thym.ui.test/src/org/eclipse/thym/ui/test/Activator.java
- tests/org.eclipse.thym.ui.test/src/org/eclipse/thym/ui/test/AllUITests.java
- tests/org.eclipse.thym.ui.test/src/org/eclipse/thym/ui/test/platforms/PlatformRemovalActionTest.java
- tests/pom.xml
> Add UI test plugin
